/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Echarts: typeof import('./components/Echarts/src/Echarts.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElText: typeof import('element-plus/es')['ElText']
    HorizontalScroll: typeof import('./components/HorizontalScroll/src/HorizontalScroll.vue')['default']
    Icon: typeof import('./components/Icon/src/Icon.vue')['default']
    Loading: typeof import('./components/Loading/src/Loading.vue')['default']
    MultiUpload: typeof import('./components/MultiUpload/src/MultiUpload.vue')['default']
    RightMenu: typeof import('./components/RightMenu/src/RightMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./components/Icon/src/SvgIcon.vue')['default']
    Verify: typeof import('./components/Verifition/src/Verify.vue')['default']
    VerifyPoints: typeof import('./components/Verifition/src/Verify/VerifyPoints.vue')['default']
    VerifySlide: typeof import('./components/Verifition/src/Verify/VerifySlide.vue')['default']
  }
}
